name: Datashare Playground - CI

on:
  push:
    branches: [ main ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  container-test-job:
    runs-on: ubuntu-latest  
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200
        env:
          ES_JAVA_OPTS: -Xms256m -Xmx256m
          discovery.type: single-node
          cluster.name: datashare
          http.compression: false
          http.cors.enabled: true
          http.cors.allow-origin: "*"
          http.cors.allow-method: OPTIONS, HEAD, GET, POST, PUT, DELETE
          indices.query.bool.max_clause_count: 20000
    
    env:
      ELASTICSEARCH_URL: http://localhost:9200
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Run the tests with bats
        run: ./test/bats/bin/bats -r test/units/

